{
 "title": "Fission User Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Function_Name",
    "query": {
     "query": "label_values(fission_function_calls_total, function_name)"
    }
   },
   {
    "name": "Path",
    "query": {
     "query": "label_values(http_requests_total, path)"
    }
   },
   {
    "name": "Function_Namespace",
    "query": {
     "query": "label_values(kube_namespace_labels, namespace)"
    }
   },
   {
    "name": "Fission_Namespace",
    "query": {
     "query": "label_values(fission_function_calls_total, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Function calls",
   "type": "timeseries",
   "description": "Shows function calls, namespaces and their response codes.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "increase(fission_function_calls_total{function_name=~\"$Function_Name\",function_namespace=~\"$Function_Namespace\"}[1m])",
     "legendFormat": "Namespace:{{function_namespace}} Func:{{function_name}} {{method}} Response: {{code}} "
    }
   ]
  },
  {
   "title": "Function Errors",
   "type": "timeseries",
   "description": "Shows any functions that return 400 or 500 errors.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "increase(fission_function_errors_total{function_name=~\"$Function_Name\",function_namespace=~\"$Function_Namespace\"}[1m])",
     "legendFormat": "Namespace:{{function_namespace}} Function:{{function_name}} Response:{{code}} "
    }
   ]
  },
  { "title": "Http Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Http Requests in Flight (function)",
   "type": "timeseries",
   "description": "Shows the number of requests currently in flight per function path",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "http_requests_in_flight{path=~\"$Path\"}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Request latency",
   "type": "timeseries",
   "description": "Shows the average latency for each path.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_requests_duration_seconds_sum{path!=\"/healthz\",path!~\"/v2/.*\",path!~\"/router.*\",path=~\"$Path\"}/http_requests_duration_seconds_count{path=~\"$Path\"}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Function cold starts",
   "type": "timeseries",
   "description": "Tracks cold starts of all functions.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(fission_function_cold_starts_total{function_name=~\"$Function_Name\",function_namespace=~\"$Function_Namespace\"}[1m])",
     "legendFormat": "{{function_name}}"
    }
   ]
  }
 ]
}