# COMP90024_team_57 - Fission spec for Reddit harvester function

apiVersion: fission.io/v1
kind: Package
metadata:
  name: reddit-harvester
spec:
  environment:
    name: python
    namespace: default
  deployment:
    type: archive
    url: ""
  source:
    type: dir
    dir: ./src/reddit_harvester
  buildcmd: "./build.sh"
---
apiVersion: fission.io/v1
kind: Function
metadata:
  name: reddit-harvester-fn
spec:
  environment:
    name: python
    namespace: default
  package:
    packageRef:
      name: reddit-harvester
  entrypoint: "reddit_fission.main"
  configmaps:
    - shared-data
---
apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  name: reddit-harvester-trigger
spec:
  functionref:
    name: reddit-harvester-fn
  url: /reddit/harvest
  method: GET