apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: bluesky-post
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 30
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  configmaps:
  - name: shared-data
    namespace: ""
  environment:
    name: go
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: PostHandler
    packageref:
      name: bluesky
      namespace: ""
  requestsPerPod: 1
  resources: {}
