apiVersion: fission.io/v1
kind: MessageQueueTrigger
metadata:
  creationTimestamp: null
  name: reddit-es-indexer-trigger
spec:
  contentType: application/json
  cooldownPeriod: 300
  errorTopic: errors-reddit-es-indexer
  functionref:
    functionweights: null
    name: reddit-to-elasticsearch
    type: name
  maxReplicaCount: 100
  maxRetries: 3
  messageQueueType: redis
  metadata:
    address: redis-headless.redis.svc.cluster.local:6379
    listLength: "10000"
    listName: reddit_posts_formatted_queue
  minReplicaCount: 0
  mqtkind: keda
  pollingInterval: 30
  topic: reddit_posts_formatted_queue
