apiVersion: fission.io/v1
kind: MessageQueueTrigger
metadata:
  creationTimestamp: null
  name: reddit-formatter-trigger
spec:
  contentType: application/json
  cooldownPeriod: 300
  errorTopic: errors-reddit-formatter
  functionref:
    functionweights: null
    name: reddit-data-formatter
    type: name
  maxReplicaCount: 100
  maxRetries: 3
  messageQueueType: redis
  metadata:
    address: redis-headless.redis.svc.cluster.local:6379
    listLength: "1000"
    listName: reddit_posts_queue
  minReplicaCount: 0
  mqtkind: keda
  pollingInterval: 30
  respTopic: reddit_posts_formatted_queue
  topic: reddit_posts_queue
