apiVersion: fission.io/v1
kind: MessageQueueTrigger
metadata:
  creationTimestamp: null
  name: oa-debate-harvester-by-person
spec:
  contentType: application/json
  cooldownPeriod: 300
  errorTopic: errors
  functionref:
    functionweights: null
    name: oa-debate-harvester-by-person
    type: name
  maxReplicaCount: 100
  maxRetries: 3
  messageQueueType: redis
  metadata:
    address: redis-headless.redis.svc.cluster.local:6379
    listLength: "1000"
    listName: oa_debate_people
  minReplicaCount: 0
  mqtkind: keda
  pollingInterval: 30
  respTopic: oa_debate_data
  topic: oa_debate_people
