include:
- ./src/open_australia/oa_debates/oa_person_lister/__init__.py
- ./src/open_australia/oa_debates/oa_person_lister/oa_person_lister.py
- ./src/open_australia/oa_debates/oa_person_lister/requirements.txt
- ./src/open_australia/oa_debates/oa_person_lister/build.sh
kind: ArchiveUploadSpec
name: src-open-australia-oa-debates-oa-person-lister---init---py-EX8x

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: oa-person-lister
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python39
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://src-open-australia-oa-debates-oa-person-lister---init---py-EX8x
status:
  buildstatus: pending
  lastUpdateTimestamp: "2025-05-04T07:23:07Z"
