include:
- src/analysis/sentiment/main.go
- src/analysis/sentiment/go.mod
- src/analysis/sentiment/go.sum
kind: ArchiveUploadSpec
name: src-analysis-sentiment-main-go-gV6Q

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: elastic-sentiment
spec:
  deployment:
    checksum: {}
  environment:
    name: go
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://src-analysis-sentiment-main-go-gV6Q
status:
  buildstatus: pending
  lastUpdateTimestamp: "2025-05-08T10:54:22Z"
