include:
- ./src/ui/sentiment/__init__.py
- ./src/ui/sentiment/sentiment.py
- ./src/ui/sentiment/bluesky.py
- ./src/ui/sentiment/reddit.py
- ./src/ui/sentiment/openaus.py
- ./src/ui/sentiment/requirements.txt
- ./src/ui/sentiment/build.sh
kind: ArchiveUploadSpec
name: src-ui-sentiment---init---py-v2Sr

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: ui-sentiment
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://src-ui-sentiment---init---py-v2Sr
status:
  buildstatus: pending
  lastUpdateTimestamp: "2025-05-10T08:16:58Z"
