include:
- ./src/open_australia/oa_debates/debate_adder/__init__.py
- ./src/open_australia/oa_debates/debate_adder/oa_debate_adder.py
- ./src/open_australia/oa_debates/debate_adder/requirements.txt
- ./src/open_australia/oa_debates/debate_adder/build.sh
kind: ArchiveUploadSpec
name: src-open-australia-oa-debates-debate-adder---init---py-t47W

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: oa-debate-adder
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python39
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://src-open-australia-oa-debates-debate-adder---init---py-t47W
status:
  buildstatus: pending
  lastUpdateTimestamp: "2025-05-05T03:55:20Z"
