include:
- ./src/reddit/reddit_harvester.py
- ./src/reddit/reddit_to_elasticsearch.py
- ./src/reddit/reddit_daily_harvester.py
- ./src/reddit/__init__.py
- ./src/reddit/util.py
- ./src/reddit/requirements.txt
- ./src/reddit/build.sh
kind: ArchiveUploadSpec
name: src-reddit-reddit-harvester-py-Kmad

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: reddit-harvester-new-r
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://src-reddit-reddit-harvester-py-Kmad
status:
  buildstatus: pending
  lastUpdateTimestamp: "2025-05-20T04:59:57Z"
