apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: oa-people-year-house
spec:
  createingress: true
  functionref:
    functionweights: null
    name: oa-person-lister
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /openaustralia/year/{year:[0-9][0-9][0-9][0-9]}/house/{house:[a-zA-Z0-9]+}
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /openaustralia/year/{year:[0-9][0-9][0-9][0-9]}/house/{house:[a-zA-Z0-9]+}
