apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: reddit-fetch-trigger
spec:
  createingress: true
  functionref:
    functionweights: null
    name: reddit-post
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /reddit/analysis
    tls: ""
  method: ""
  methods:
  - POST
  prefix: ""
  relativeurl: /reddit/analysis
