apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: reddit-query-trigger-new
spec:
  createingress: false
  functionref:
    functionweights: null
    name: reddit-query-trigger-new
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /reddit-new/scrape/
    tls: ""
  method: ""
  methods:
  - POST
  prefix: ""
  relativeurl: /reddit-new/scrape/
