apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: ui-named-entity
spec:
  createingress: true
  functionref:
    functionweights: null
    name: ui-named-entity
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /ui/named-entities/count/{count:[0-9]+}/label/{label:[a-zA-Z0-9]+}
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /ui/named-entities/count/{count:[0-9]+}/label/{label:[a-zA-Z0-9]+}
