apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: vader-sentiment-function
spec:
  createingress: true
  functionref:
    functionweights: null
    name: vader-sentiment-function
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /analysis/sentiment/v1
    tls: ""
  method: ""
  methods:
  - POST
  prefix: ""
  relativeurl: /analysis/sentiment/v1
