apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: gui-sentiment
spec:
  createingress: true
  functionref:
    functionweights: null
    name: gui-sentiment
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /ui/sentiment/start/{date:[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]}/
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /ui/sentiment/start/{date:[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]}/
