apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: shared-data
data:
  ES_USERNAME: elastic
  ES_PASSWORD: Mi0zu6yaiz1oThithoh3Di8kohphu9pi
  ES_FINGERPRINT: 5FD336DE4088D4F31C833275E9085871186FDBA6C92938C14B3C89D868AAE404

